version: '3'

services:
  api:
    build:
      context: .
      args:
        port: 8000
        app_env: production
    volumes:
      - .:/go/src/github.com/TailorDev/crick/api
    environment:
      CRICK_DSN: postgres://crick:crickIsChic@db:5432/crick?sslmode=disable
      AUTH0_DOMAIN: https://lefitz.eu.auth0.com/
      AUTH0_AUDIENCE: q2V4JTCWPiMtu5C4KVIadLyv1bLIOMJx,https://lefitz.eu.auth0.com/userinfo
      AUTH0_JWKS_URI: https://lefitz.eu.auth0.com/.well-known/jwks.json
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: crick
      POSTGRES_USER: crick
      POSTGRES_PASSWORD: crickIsChic
